### ISSUE TITLE
Drop-down menu with Title of scenario's instead of ID

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#94] opened 2015-05-07 10:16 UTC
Now you have to remember your ID somehow which is not very user-friendly:
![ivy](https://cloud.githubusercontent.com/assets/1303760/7513232/e450b492-f4b2-11e4-821e-f6c1e3633e26.png)

**Comment by grdw** [comment] 2015-05-07 14:05
Duplicate of #95

**Closed by grdw** 2015-05-07 14:05 UTC
Labels: Enhancement
