### ISSUE TITLE
It seems that the topology only shows the 'demand' of the nodes

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#9] opened 2015-01-27 15:24 UTC
![ivy](https://cloud.githubusercontent.com/assets/1303760/5920933/96774a94-a640-11e4-93f8-129ac9dd6e3f.png)

I would expect the nodes in the topology to show the sum of 'capacity' and 'demand' (which should both be called 'load' but that is a separate issue :wink: )

**Comment by antw** [comment] 2015-01-27 16:03
I'll close this since the problem is gone with the introduction of the non-Refinery calculator.

The 8.2 came from treating supplier and consumer technologies separately. The "flow" through the `LV1` node was 8.2 since the attached electric car technology needed that much energy. 2.5 of that would have been provided by the heat pump (don't ask me how a heat pump powers an electric car) and the rest from the `MV network`.

In the new calculator, technologies are *completely* invisible to the network calculation and you'll see the expected 5.7 load instead.

It would have been better had I subtracted the supply from demand before showing it in the diagram, but that's water under the bridge now...

**Closed by antw** 2015-01-27 16:03 UTC
Labels: bug

**Comment by ChaelKruip** [comment] 2015-01-27 16:07
>  (don't ask me how a heat pump powers an electric car) 

:laughing:
